version: '2'
services:
  db:
    image: mysql:5.6
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
    command:
    - mysqld
    - --character-set-server=utf8
    - --collation-server=utf8_unicode_ci 
    - --innodb-file-per-table=ON
    - --sync-frm=0
    - --innodb-flush-log-at-trx-commit=0
    - --innodb-doublewrite=0
    - --innodb-checksums=0
    - --innodb-buffer-pool-size=500M
    - --innodb-support-xa=0 
    - --datadir=/tmpfs/datadir
    - --tmpdir=/tmpfs/tmpdir
    tmpfs:
    - /tmpfs/datadir:size=800M
    - /tmpfs/tmpdir:size=200M
  web:
    build: .
    command: /sbin/init
    volumes:
    - .:/code
    depends_on:
    - db
    volumes:
    - .:/code
